# Set list of toolchains supported on this board
set_board_info target_install ${target_triplet}

# Load generic gdb configuration to bring in basic set of routines
load_generic_config "gdb-comm"

# No multilib options needed by default
process_multilib_options ""

# Specify compilers to use
set_board_info compiler [find_gcc]

# GDB protocol to be used
set_board_info gdb_protocol "remote"

# TODO: We need to define the symbols for the two co-ordiantes so that the
# linker script can do its job properly and map to the correct core. As I
# am only testing with one core, so be it.
# The port also depends on this, but we will use the default one...
#set_board_info netport 51000
# We store the board address as a variable as we use it twice later
set tmp_board [exec [file dirname $env(DEJAGNU)]/get-ip.sh --rotate]
set_board_info netport $tmp_board

# Set board specific linker script to do mapping
set_board_info ldscript [exec [file dirname $env(DEJAGNU)]/getcoords.sh $tmp_board]

# Use 'continue' instead of 'run' when executing a test
set_board_info gdb_run_command "continue"

# No support for passing arguments
set_board_info noargs 1
set_board_info gdb,noargs 1

# No IO (don't know really, but sounds good to me)
set_board_info gdb,noinferiorio 1

# Same for signals and return results
set_board_info gdb,nosignals  1

# GDB can't return results
#set_board_info gdb,noresults 1

# Restrict stack size for gcc torture tests
set_board_info gcc,stack_size 2048


